image: ruby:latest

before_script:
  - gem install bundler:1.17.3
  - bundle config set clean true
  - bundle config set jobs $(nproc)
  - bundle config set path vendor/bundle
  - bundle install

cache:
  paths:
    - vendor/bundle

test:
  stage: test
  script:
    - bundle exec jekyll build -d test
  artifacts:
    paths:
      - test
  except:
    - master
    - gitlab

pages:
  stage: deploy
  script:
    - bundle exec jekyll build -d public
  artifacts:
    paths:
      - public
  only:
    - master
    - gitlab
